# The 'acl' package is required for 'become' in ansible to work.
# The 'libpq-dev' is for building the 'psycopg2' requirement.
- name: "Install packages"
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - python3-pip
      - python3-venv
      - acl
      - libpq-dev

- name: "Upgrade pip to latest and greatest version"
  pip:
    name: pip
    extra_args: --upgrade