version: "3"
services:
  yacht:
    container_name: yacht
    restart: unless-stopped
    ports:
      - 8001:8000
    volumes:
      - /docker/containers/yacht/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    image: selfhostedpro/yacht

volumes:
  yacht:
