version: "3.9"
services:
  mssql:
    container_name: mssql
    hostname: mssql
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    env_file: "${CONFIG}/mssql/mssql.env"
    ports:
      - "16433:1433"
    volumes:
      - "${DATAROOT}/localdb:/sql"
    environment:
      - "SA_PASSWORD=105022_Alpha"
      - "ACCEPT_EULA=Y"
      - "MSSQL_MEMORY_LIMIT_MB=6144"
      - "MSSQL_AGENT_ENABLED=true"
      - "MSSQL_BACKUP_DIR=/sql/backup"
      - "MSSQL_DATA_DIR=/sql/data"
      - "MSSQL_LOG_DIR=/sql/log"
      - "MSSQL_ERROR_LOG_FILE=/sql/error/error.log"
      - "MSSQL_DUMP_DIR=/sql/dump"
      - "MSSQL_PID=Developer" #Standard, Enterprise, Developer
      - "MSSQL_TCP_PORT=16433"
      #- "MSSQL_IP_ADDRESS=127.0.0.1"
      #- "MSSQL_MEMORY_LIMIT_MB=4096"
    restart: always
    networks:
      pyrodb:
        ipv4_address: 172.21.0.10
  # postgres:
  #   container_name: postgres
  #   hostname: postgres
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - "${DATAROOT}/postgres/data:/var/lib/postgresql/data/"
  #   environment:
  #     - POSTGRES_USER=efras
  #     - POSTGRES_PASSWORD=105022_Alpha
  #   restart: always
  #   networks:
  #     pyrodb:
  #       ipv4_address: 172.21.0.20
  # pgadmin:
  #   container_name: pgadmin
  #   hostname: pgadmin
  #   image: dpage/pgadmin4
  #   env_file: "${CONFIG}/pgadmin/pgadmin.env"
  #   ports:
  #     - "15432:80"
  #   volumes:
  #     - "C:/env/pgsql/pgAdmin4:/var/lib/pgadmin"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: efraser25@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: 105022_Alpha
  #     PGADMIN_LISTEN_PORT: 80
  #   restart: always
  #   depends_on:
  #     - postgres
  #   networks:
  #     pyrodb:
  #       ipv4_address: 172.21.0.21
networks:
  pyrodb:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
