version: "3.3"

networks:
  ntw_front:
    external: true

services:

  traefik:
    image: devmtl/traefikfire:1.3.8A
    networks:
      - ntw_front
    ports:
      - mode: ingress
        published: 80
        target: 80
      - mode: host
        published: 8080
        target: 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --docker \
      --docker.watch \
      --docker.swarmmode \
      --docker.endpoint=unix:///var/run/docker.sock \
      --docker.domain=traefik \
      --docker.exposedbydefault=true \
      --entryPoints='Name:http' \
      --debug=true \
      --logLevel=WARN \
      --web \
      --web.metrics \
      --web.metrics.prometheus \
      --web.metrics.prometheus.buckets="0.1,0.3,1.2,5.0" \
      --web.address=:8080
    deploy:
      # If you don't want to access the dashboard
      #labels:
      #- "traefik.enable=false"
      mode: replicated
      replicas: 1
      update_config:
        delay: 2s
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
        max_attempts: 5
      resources:
        limits:
          cpus: '0.33'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 64M


# mode: ingress / must run in a docker swarm
#
#devmtl/traefikfire:1.3.8A
#traefik:1.4.0-alpine
#
#- traefik-pub:/etc/traefik/acme
#
#--docker.endpoint=unix:///var/run/docker.sock \
#--docker.endpoint=tcp://socat:2375 \
#
# no acme
#
# Inspired by https://github.com/containous/traefik/issues/766#issuecomment-335208880
#
# Log options: "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "PANIC"
# https://github.com/containous/traefik/commit/af9b63eaed828f1d548f404fc8b486dd592184e9
#
#--acme.entrypoint=https \
#--acme=true \
#--acme.domains='${CLUSTER_PUBLIC_DOMAIN}' \
#--acme.email=${ACME_EMAIL} \
#--acme.ondemand=true \
#--acme.onhostrule=true \
#--acme.storage=/etc/traefik/acme/acme.json \
#
# by Pascal Andy | # https://twitter.com/askpascalandy
# https://github.com/pascalandy/docker-stack-this
#