version: '3.9'

services:
  example_echo_02_01:
    image: ealen/echo-server:latest
    container_name: "example_echo_02_01"
    environment:
      - SERVICENAME=example_echo_02_01
      - TZ=Africa/Johannesburg
      - PGID=1000
      - PUID=1000
      - UMASK=002
      - VERSION=docker
      - VIRTUAL_HOST=`example_echo_02_01.${DOCKER_HOST_URL}`
    expose: 
      - "80"
    labels:   
      - "traefik.enable=true"
      - "traefik.http.routers.example_echo_02_01.entrypoints=websecure"
      - "traefik.http.routers.example_echo_02_01.rule=Host(`example_echo_02_01.${DOCKER_HOST_URL}`) || ( Host(`${DOCKER_HOST_URL}`) && PathPrefix(`/example_echo_02_01`) )" 
      - "traefik.http.routers.example_echo_02_01.tls=true"
      - "traefik.http.services.hellowoexample_echo_02_01rld_02_01.loadbalancer.server.port=80"
    networks: 
      - tnet-global
    ports:
      - target: 80
        published: 93
        protocol: tcp
    volumes:
      - type: volume
        source: global_certs
        target: "/certs"
      - type: bind
        source: "/docker/mini/network/nets/configs"
        target: "/config"
    restart: always
    
  whoami_02_02:
    image: containous/whoami
    container_name: "whoami_02_02"
    environment:
      - SERVICENAME=whoami_02_02    
      - TZ=Africa/Johannesburg
      - PGID=1000
      - PUID=1000
      - UMASK=002
      - VERSION=docker
      - VIRTUAL_HOST=`whoami_02_02.${DOCKER_HOST_URL}`
    labels:   
      - "traefik.enable=true"
      - "traefik.http.routers.whoami_02_02.entrypoints=websecure"
      - "traefik.http.routers.whoami_02_02.rule=Host(`whoami_02_02.${DOCKER_HOST_URL}`) || ( Host(`${DOCKER_HOST_URL}`) && PathPrefix(`/whoami_02_02`) )" 
      - "traefik.http.routers.whoami_02_02.tls=true"
      - "traefik.http.services.whoami_02_02.loadbalancer.server.port=80"
    networks: 
      - tnet-global
    ports:
      - target: 80
        published: 94
        protocol: tcp
    volumes:
      - type: volume
        source: global_certs
        target: "/certs"
      - type: bind
        source: "/docker/mini/network/nets/configs"
        target: "/config"
    restart: always    

volumes:    
  global_certs:
    name: global_certs
    external: true

networks:
  tnet-global:
    external: true
    #name: cnet_02
