- name: "Configure SSL Certificates"
  import_tasks: ssl/certificates.yml

- name: "Configuring Apache"
  import_tasks: apache/server.yml
  when: web.server == 'apache'

- name: "Configuring nginx"
  import_tasks: nginx/server.yml
  when: web.server == 'nginx'