# Before running this container, make sure that the url and subdomains are properly forwarded to this container's host, and that port 443 (and/or 80) is not being used by another servic
# duckdns validation, either leave the SUBDOMAINS variable empty or set it to wildcard, and set the DUCKDNSTOKEN
# Due to limitation of duckdns, the cert will only cover either main subdomain (ie. yoursubdomain.duckdns.org), or sub-subdomains (ie. *.yoursubdomain.duckdns.org), but will not both at the same time.i
# For dynamic dns provider, you can use the free provider duckdns.org; the URL will be yoursubdomain.duckdns.org & SUBDOMAINS can be www,ftp,cloud with http validation, or wildcard with dns validation. 
#After setup, navigate to https://yourdomain.url to access the default homepage (http access through port 80 is disabled by default, you can enable it by editing the default site config at /config/nginx/site-confs/default).
# Certs are checked nightly and if expiration is within 30 days, renewal is attempted
# For dns validation, make sure to enter your credentials into the corresponding ini (or json for some plugins) file under /config/dns-conf
# Cloudflare provides free accounts for managing dns and is very easy to use with this image. Make sure that it is set up for "dns only" instead of "dns + proxy"
# The default site config resides at /config/nginx/site-confs/default
    #image: lscr.io/linuxserver/swag 

version: "3.9"
services:
  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - SERVICENAME=swag
      - VERSION=docker 
      - TZ=Africa/Johannesburg
      - PGID=1000
      - PUID=1000
      - DOMAIN=docker.local
      - VIRTUAL_HOST=swag.docker.local
     # - CERTPROVIDER= #optional
     #- DNSPLUGIN=cloudflare #optional
     #- DUCKDNSTOKEN=<token> #optional
      - EMAIL=efraser25@gmail.com #optional
     # - EXTRA_DOMAINS=<extradomains> #optional
     #  - ONLY_SUBDOMAINS=false #optional
     #  - STAGING=false #optional
      - SUBDOMAINS=www #wildcard #www,
      - URL=portainer.docker.local
      - VALIDATION=http #dns,http,duckdns
    volumes:
      - type: bind
        source: /docker/certs/swag
        target: /config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
