version: '3.9'

services:
  whoami:
    image: containous/whoami
    container_name: whoami
    environment:
      - SERVICENAME=whoami    
      - TZ=Africa/Johannesburg
      - PGID=1000
      - PUID=1000
      - UMASK=002
      - VERSION=docker
      - VIRTUAL_HOST=whoami.${DOCKER_HOST_URL}
    labels:   
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOCKER_HOST_URL}`)" 
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
    networks: 
      - traefik_public
    ports:
      - target: 80
        published: 92
        protocol: tcp
    volumes:
      - type: volume
        source: global_certs
        target: "/certs"
      - type: bind
        source: "/docker/mini/network/nets/configs"
        target: "/config"
    restart: always    

volumes:
  global_certs:
    name: global_certs
    external: true

networks:
  traefik_public:
    external: true
    #name: cnet_01
