http:
  routers:
    https-redirect:
      rule: 'HostRegexp(`{any:.*}`)'
      middlewares:
       - https-redirect
      service: redirect-all
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
  services:
    redirect-all:
      loadBalancer:
        servers:
         - url: ""

tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      cipherSuites:
        - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
