###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
log_level: debug
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
jwt_secret: YOUR_SECRET_VALUE
default_redirection_url: http://public.example.com
totp:
  issuer: examle.com

authentication_backend:
  disable_reset_password: false
  file:
    path: /config/users_database.yml
    password:
      algorithm: sha512
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: public.example.com
      policy: bypass
    - domain: whoami.example.com
      policy: one_factor
    - domain: grafana.example.com
      policy: two_factor
    - domain: nodered.example.com
      policy: two_factor

session:
  name: EXAMPLE_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: YOUR_SECRET_VALUE
  expiration: 1M # 1 month
  inactivity: 2w # 2 week
  domain: example.com # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  smtp:
    username: user
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    password: password
    host: smtp-with-tls.mail.example.com
    port: 25
    sender: email@example.com
