
version: "3.9"
services:
  traefik_new:
    container_name: traefik_new    
    image: traefik:latest
    env_file: /docker/stacks/airtraffic/configs/traefik/traefik.env
    environment:
      - SERVICENAME=sabnzbd
      - VIRTUAL_HOST=traefik.${DOCKER_BASE_URL}
      - TZ=Africa/Johannesburg
      - PGID=1000
      - PUID=1000
      - UMASK=002
      - VERSION=docker    
#    command: 
#      - "--providers.docker"
#      - "--providers.file.watch=true"  
#      - "--entrypoints.web.address=:80"
#      - "--entrypoints.websecure.address=:443"
#      - "--providers.docker.exposedbydefault=false"
#      - "--api.insecure=true"
#      - "--api.dashboard=true"
#      - "--log.level=DEBUG"
#      - "--accessLog.filePath=/log/traefik.log"   
#      - "--accesslog=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-http.entrypoints=web"
      - "traefik.http.routers.traefik-http.rule=Host(`traefik.${DOCKER_BASE_URL}`) || Host(`${DOCKER_BASE_URL}`)"
      - "traefik.http.routers.traefik-http.middlewares=traefik-https"
      - "traefik.http.middlewares.traefik-https.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.rule=( Host(`${DOCKER_BASE_URL}`) && PathPrefix(`/sabnzbd`) )" 
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    networks:
      - traefik_public
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
      - target: 8080
        published: 8080
        protocol: tcp  
    volumes:
      - type: volume
        source: global_certs
        target: "/certs"        
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock         
      - type: bind
        source: /docker/stacks/airtraffic/configs/traefik
        target: /configs
      - type: bind
        source: /docker/stacks/airtraffic/logs/traefik.log
        target: /log/traefik.log   
    restart: always


    # Global mode makes an instance of traefik listen on _every_ node, so that regardless of which
    # node the request arrives on, it'll be forwarded to the correct backend service.
   # deploy:
   #   mode: global
   #   labels:
   #     - "traefik.docker.network=traefik_public"
   #     - "traefik.http.routers.api.rule=Host(`traefik.example.com`)"
   #     - "traefik.http.routers.api.entrypoints=https"
   #     - "traefik.http.routers.api.tls.domains[0].main=example.com"
   #     - "traefik.http.routers.api.tls.domains[0].sans=*.example.com"        
   #     - "traefik.http.routers.api.tls=true"
   #     - "traefik.http.routers.api.tls.certresolver=main"
   #     - "traefik.http.routers.api.service=api@internal"
   #     - "traefik.http.services.dummy.loadbalancer.server.port=9999"

        # uncomment this to enable forward authentication on the traefik api/dashboard
        #- "traefik.http.routers.api.middlewares=forward-auth"      
   #   placement:
   #     constraints: [node.role == manager]

networks:
  traefik_public:
    name: traefik_public
    driver: bridge
#    driver_opts:
#      com.docker.network.enable_ipv6: "true"
    attachable: true
    external: false
    
    
volumes:
  global_certs:
    name: global_certs
    external: true


