# This stack exists solely to deploy the traefik_public overlay network so that other stacks (including traefik-app) can attach to it
version: "3.9"

services:
  public_scratch:
    image: hello-world:latest
    container_name: public_scratch
    networks:
      - public 
    restart: always

networks:
  public:
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 192.168.16.0/24
