version: '3.9'
services:
  
  portainer:   
    container_name: portainer
    hostname: portainer
    image: portainer/portainer-ce:latest
    environment:
      - SERVICENAME=portainer
      - VERSION=docker
      - TZ=Africa/Johannesburg
      - DOMAIN=docker.internal
      - VIRTUAL_HOST=portainer
      - URL=portainer.docker.internal
    ports:   
      - 9444:9443
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /docker/containers/drydock/portainer/data
        target: /data
      - type: bind
        source: /docker/certs
        target: /certs
    restart: always
