version: '3.1'

# — — — # — — — # — — — #
# NOT WORKING AT THE MOMENT
# See the readme for the `docker service create instead`
# — — — # — — — # — — — #

services:

  tool-socketproxy:
    image: rancher/socat-docker
    networks:
      - ntw_socketproxy
    volumes:
      - /var/run/docker.sock,target=/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]                                           
      restart_policy:
        condition: on-failure

  tool-traefik:
    image: traefik:1.3.0-alpine
    command: --web --docker --docker.swarmmode --docker.watch --docker.domain=traefik --docker.endpoint=tcp://socketproxy:2375 --logLevel=DEBUG
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - ntw_front
      - ntw_socketproxy
    depends_on:
      - "socketproxy"
    deploy:
      mode: global
      placement:
        constraints: [node.role == worker]                                           
      restart_policy:
        condition: on-failure
      
networks:
  ntw_front:
  ntw_socketproxy:
    external: true
    