kind: ConfigMap
apiVersion: v1
metadata:
  name: omgwtfssl
data:
  SSL_SUBJECT: "*.192.168.99.100.xip.io"
  SSL_IP: "192.168.99.100"
  SSL_EXPIRE: "3600"
  SILENT: "true"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: omgwtfssl
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: omgwtfssl
        image: paulczar/omgwtfssl:latest
        envFrom:
        - configMapRef:
            name: omgwtfssl
        volumeMounts:
        - name: certs-path
          mountPath: /certs
      containers:
      - name: kubectl
        image: lachlanevenson/k8s-kubectl:v1.9.3
        command: ["kubectl", "apply", "-f", "/certs/secret.yaml"]
        volumeMounts:
        - name: certs-path
          mountPath: /certs
      volumes:
      - name: certs-path
        emptyDir: {}