version: "3.2"

services:

  #home:
  # With a real domain you should use:
  # - "traefik.frontend.rule=Host:mydummysite.tk"
  
  who1:
    image: abiosoft/caddy
    networks:
      - ntw_front
    deploy:
      replicas: 2
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.20'
          memory: 12M
      labels:
        - "traefik.backend=who1"
        - "traefik.frontend.rule=PathPrefixStrip:/who1"
        - "traefik.port=2015"
        - "traefik.docker.network=ntw_front"
        - "traefik.backend.loadbalancer.method=wrr"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.weight=10"

  who2:
    image: nginx:alpine
    networks:
      - ntw_front
    deploy:
      replicas: 2
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.20'
          memory: 12M
      labels:
        - "traefik.backend=who2"
        - "traefik.frontend.rule=PathPrefixStrip:/who2"
        - "traefik.port=80"
        - "traefik.docker.network=ntw_front"
        - "traefik.backend.loadbalancer.method=wrr"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.weight=10"

  who3:
    image: emilevauge/whoami
    networks:
      - ntw_front
    deploy:
      replicas: 2
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.20'
          memory: 7M
      labels:
        - "traefik.backend=who3"
        - "traefik.frontend.rule=PathPrefixStrip:/who3"
        - "traefik.port=80"
        - "traefik.docker.network=ntw_front"
        - "traefik.backend.loadbalancer.method=wrr"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.weight=10"

networks:
  ntw_front:
    external: true

### ### ### ### ### ### ### ### ### ### ### ### ### ### 

#wrr: Weighted Round Robin
#drr: Dynamic Round Robin

# Example
# "traefik.frontend.passHostHeader=true"

#Cheers!
#Pascal | https,http://twitter.com/askpascalandy

### ### ### ### ### ### ### ### ### ### ### ### ### ###