version: "3.2"

# pre-Requirement
# Don't forget to set acme.json on the node

# Log options: "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "PANIC"
  # https://github.com/containous/traefik/commit/af9b63eaed828f1d548f404fc8b486dd592184e9

services:

  traefik:
    image: traefik:1.3.8
    command:
      - --docker
      - --docker.swarmmode=true
      - --docker.domain=docker.localhost
      - --docker.watch=true
      - --docker.exposedbydefault=true
      - --docker.endpoint=unix:///var/run/docker.sock
      - --debug=true
      - --logLevel=WARN
      - --web
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - ntw_front
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/DeployGRP/tooldata/traefik/acme.json:/etc/traefik/acme/acme.json
      - /root/docker-stack-this/traefik-manager/traefik-config/traefik.toml:/etc/traefik/traefik.toml
      #- /root/docker-stack-this/traefik-manager/traefik-config/demoselfsign.crt:/etc/traefik/demoselfsign.crt
      #- /root/docker-stack-this/traefik-manager/traefik-config/demoselfsign.key:/etc/traefik/demoselfsign.key
    labels:
      - "traefik.enable=false"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
        reservations:
          cpus: '0.10'
          memory: 64M

networks:
  ntw_front:
    external: true

#Cheers!
#Pascal | https://twitter.com/askpascalandy
