---
- name: "Install prerequisites"
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  roles:
    - prerequisites

- name: "Install DBMS"
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  roles:
    - dbms

- name: "Install SnitchDNS"
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  roles:
    - snitch

- name: "Install SnitchDNS Service"
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  roles:
    - service

- name: "Configure web server"
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  roles:
    - webserver

- name: "Configure iptables"
  hosts: all
  become: yes
  vars_files:
    - vars.yml
  roles:
    - iptables