version: '3.8'

# This stack exists solely to deploy the traefik_public overlay network, so that
# other stacks (including traefik-app) can attach to it

services:
  scratch:
    image: scratch
    deploy:
      replicas: 0
    networks:
      - traefiknet

networks:
  traefiknet:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 172.16.10.0/24