bind:
  image: sameersbn/bind:latest
  dns: 127.0.0.1
  environment:
    - ROOT_PASSWORD=105022_Alpha
  ports:
   - 192.168.68.120:10000:10000
   - 192.168.68.120:53:53/udp
  volumes:
    - /srv/docker/bind:/data
