version: "3.9"
services:
  alpine:
    container_name: alpine
    hostname: alpine
    #image: "alpine:latest"
    build: .
    env_file: "${SERVICEROOT}/alpine/alpine.env"
   # command: tail -f /dev/null
    networks:
        pyroos:
          ipv4_address: 172.15.0.10  
    volumes:
      - "${SERVICEROOT}/alpine/config:/conf"
      - "${SERVICEROOT}/alpine/script:/scr"
    restart: always

networks:
  pyroos:
    ipam:
        driver: default
        config:
            - subnet: 172.15.0.0/24    

