[tls]

[tls.stores]

[tls.stores.default]

[tls.stores.default.defaultCertificate]
certFile = "/certs/delaporte.manakin-velociraptor.ts.net.pem"
keyFile = "/certs/delaporte.manakin-velociraptor.ts.net-key.pem"


